ktor {
    deployment {
        port = 8080
        port = ${?PORT}
    }
    application {
        modules = [ com.pecadoartesano.ApplicationKt.module ]
    }
}
#jwt {
#    secret = jwtSecret
#    issuer = jwtIssuer
#    domain = "http://0.0.0.0:8080"
#    audience = jwtAudience
#    realm = jwtRealm
#    expiration = 3600000
#}

#database {
#  url = "jdbc:postgresql://localhost:5433/${DB_NAME}"
#  user = DB_USER
#  password = DB_PASSWORD
#}